// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuxibaAccesos.Api.Data;

#nullable disable

namespace NuxibaAccesos.Api.Migrations
{
    [DbContext(typeof(AccesosDbContext))]
    [Migration("20260924034051_CrearTablasIniciales")]
    partial class CrearTablasIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NuxibaAccesos.Api.Models.Area", b =>
                {
                    b.Property<int>("IDArea")
                        .HasColumnType("int");

                    b.Property<string>("AreaName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusArea")
                        .HasColumnType("int");

                    b.HasKey("IDArea", "AreaName");

                    b.ToTable("ccRIACat_Areas", (string)null);
                });

            modelBuilder.Entity("NuxibaAccesos.Api.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Extension")
                        .HasColumnType("int");

                    b.Property<int>("TipoMov")
                        .HasColumnType("int");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("User_id", "fecha");

                    b.ToTable("ccloglogin");
                });

            modelBuilder.Entity("NuxibaAccesos.Api.Models.Usuario", b =>
                {
                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IDArea")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAttempt")
                        .HasColumnType("datetime");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoUser_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("fCreate")
                        .HasColumnType("datetime");

                    b.HasKey("User_id");

                    b.ToTable("ccUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
